language: python

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="lua=5.4"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks ~/lua -r^ --$LUA
  - export PATH=$PATH:$HOME/lua/bin:$HOME/.luarocks/bin

install:
  - make dev-deps

script:
  - make test

after_success:
  - luacov -r lcov
  - bash <(curl -s https://codecov.io/bash) -f luacov.report.out
